### ISSUE TITLE
Deprecated function each()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/user_import#10]
When uploading a file get this error. Using PHP 7.2.

> Deprecated function: The each() function is deprecated. This message will be suppressed on further calls in user_user_import_edit_roles_fields() (line 211 of /app/modules/user_import/supported/user.inc).

**Comment by laryn** [comment]
Looks like maybe a new release is coming soon for Drupal, including this fix:

https://www.drupal.org/project/user_import/issues/3015689

**Comment by laryn** [comment]
Should be fixed in latest dev; I pulled the latest commits from Drupal including this one:
https://github.com/backdrop-contrib/user_import/commit/477b6e38b2ba21d67afa728ac5820fe0a99d5328
