### ISSUE TITLE
Deprecated function file_create_htaccess()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/user_import#11]
When uploading a CSV file:

> The function user_import_create_directory() (user_import.admin.inc:1072) called deprecated function file_create_htaccess(). It will be removed in the next major release of Backdrop.

**Comment by laryn** [comment]
Looks like it just needs to be switched to `file_save_htaccess`.
https://api.backdropcms.org/api/backdrop/core%21includes%21drupal.inc/function/file_create_htaccess/1
Thanks!
