### ISSUE TITLE
I get a fatal error when choosing to update existing users with import

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/user_import#12]
I get a warning:

> Warning: Attempt to assign property of non-object in _user_import_process() (line 96 of /var/httpdocs/modules/user_import/user_import.import.inc).

and a fatal error:

> Error: Call to a member function save() on array in user_save() (line 314 of /var/httpdocs/core/modules/user/user.module).

Looks like the user object isn't being created properly somewhere and it's passing an array instead.

**Comment by laryn** [comment]
@herbdool I'll try to give this a look but I'm going to be away from the computer in the next little while. Vacation! If you solve it in the meantime, feel free to PR it.

**Comment by laryn** [comment]
@herbdool Can you test the latest dev? I pulled a bunch of commits from the Drupal module and then had to do a bunch of tweaking. I ran a basic user update during testing and  didn't get this error anymore.
