### ISSUE TITLE
after import field_custom is blank

### ISSUE THREAD

**Issue by scialo** [backdrop-contrib/user_import#14]
in settings:

(CVS COLUMN) field custom -> (BACKDROP FIELDS) field_custom

after import field_custom is blank.

field_custom is text short

why?

**Comment by laryn** [comment]
Hi @scialo and thanks for the report. 

I haven't actually done any testing related to imports to custom fields. Are you able to provide any more information in terms of errors or watchdog/log messages?

If you are able to figure it out and submit a PR here that is very welcome, too!

**Comment by scialo** [comment]
the import finished without error but custom fields are empty.

**Comment by Retsell** [comment]
I've also found that custom fields don't load, although no errors reported.

**Comment by antijingoist** [comment]
Might be missing something, but it doesn't appear that _user_import_process continues with additional fields once the username and email address are imported. 
Fields seem to be: 
> roles
> email
> timezone
> status
> init(?), containing an email address
> password
> access
> login

**Comment by laryn** [comment]
@antijingoist @Retsell Does this work in the Drupal 7 version, if you happen to know? I haven't used this feature myself.

`init` is the email address that was initially signed up with, and it doesn't change even if the user later changes their email address, I believe.

**Comment by antijingoist** [comment]
I used this in this way in Drupal 7, but that was years ago.

**Comment by laryn** [comment]
Maybe there's something to do with User accounts being entities rather than arrays... I'll try to look into this further, but it may be next month.

**Comment by laryn** [comment]
@antijingoist Can you test https://github.com/backdrop-contrib/user_import/commit/193fd8cca655206879725f39bc9d2109e4fb2c27 ?

**Comment by antijingoist** [comment]
This works. 2,000 users imported with integer, text and long text

**Comment by laryn** [comment]
Awesome, thanks for testing!
