### ISSUE TITLE
User Import will not import anything

### ISSUE THREAD

**Issue by Egmund** [backdrop-contrib/user_import#16]
uset_import will not import anything. Import tests OK, but I can not figure out any way to actually import. Tried 'continue' as well as 'run cron' nothing imported. Nothing in 'latest logmessages'.
What now?

**Comment by laryn** [comment]
Can you provide more info about the import you are trying? Which fields, etc? I assume you are using the latest release?

**Comment by Egmund** [comment]
Current version / latest release 1.x-3.2.1 - and newest bd.
Fields are created in bd and mapped - otherwise the test would also fail, no?

**Comment by Egmund** [comment]
Here is some odd from server error-log:
[03-Oct-2021 14:13:29 Europe/Copenhagen] PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in /home/buddhistisk/bdrop.buddhistisksamfund.dk/modules/user_import/user_import.import.inc on line 320

**Comment by laryn** [comment]
What version of PHP?

**Comment by Egmund** [comment]
7.4 but can be changed

**Comment by laryn** [comment]
Should be a hopefully quick fix for PHP 7.4:

https://stackoverflow.com/questions/59158548/array-and-string-offset-access-syntax-with-curly-braces-is-deprecated

Would you like to make a PR to fix it? Otherwise I will try to do so when I’m back in the office. You could also temporarily revert to PHP 7.3 and try that for now.

**Comment by laryn** [comment]
@Egmund I got a quick moment to fix the deprecated curly braces -- can you test this change and see if it fixes the import problem for you?
https://github.com/backdrop-contrib/user_import/commit/2167c3ee77cb90397010b688456e8cdec1617bba

**Comment by laryn** [comment]
I did a quick test and something between this commit and now seems to silently break something. 
https://github.com/backdrop-contrib/user_import/tree/193fd8cca655206879725f39bc9d2109e4fb2c27

If someone is in a pinch, this Zip file contains the module in a functional form:
https://github.com/backdrop-contrib/user_import/archive/193fd8cca655206879725f39bc9d2109e4fb2c27.zip

**Comment by laryn** [comment]
Thanks for filing the issue @Egmund -- it helped me track down a typo as well as fix the warning related to the PHP 7.4 "curly brace" deprecation. I'll make a new release today.

**Comment by Egmund** [comment]
Congratulation!!! It worked at first shot as intended. All my users are now in Backdrop

**Comment by Egmund** [comment]
- except I can not get it to import roles

**Comment by laryn** [comment]
👍 RE: roles, it looks like that is an open issue:
https://github.com/backdrop-contrib/user_import/issues/15

The check boxes on the import form should function as a work around until I can fix that. Feel free to post relevant info and log errors on that thread if you like!

**Comment by Egmund** [comment]
Funny; one role got imported. For me it is not that important at this point. I just have a few roles to manually add.
But the way to separate several roles does not work either. Only the first role of the one person got imported.

**Comment by Egmund** [comment]
Oh, I get it: Splitting imports up per role.

**Comment by laryn** [comment]
@Egmund You may be finished importing and updating roles, but if not... Try the latest version.

**Comment by Egmund** [comment]
It actually was the latest - did an uninstal  install - and - as said - it worked (with some minor flaws). Thank you for your work. Maybe there is still some hope for a backdrop site (need to find needed modules).
