### ISSUE TITLE
Import creates only one account, with last values per column

### ISSUE THREAD

**Issue by Fiselier** [backdrop-contrib/user_import#21]
Using the User_import module I only can import one account, which username is created from the first data, but is populated with the las values in the CSV. I also tried the sample.txt which resulted in the creation of 12345 ONeil but with first name Ernest and last name Wilson (#36 in the CSV). When there are empty cells, the last known value is used...
![Screenshot 2024-01-04 181300](https://github.com/backdrop-contrib/user_import/assets/6840049/f72bbe7a-1682-4368-9778-989d885c5149)

**Comment by laryn** [comment]
Thanks @Fiselier -- I haven't used this module in a while but I think it's a handy one. Can you update with some details such as PHP version, Backdrop version, etc.?

**Comment by Fiselier** [comment]
> Thanks @Fiselier -- I haven't used this module in a while but I think it's a handy one. Can you update with some details such as PHP version, Backdrop version, etc.?

Hi @laryn, I've put my status report below. I started with a clean BD installation and wanted to import a csv with my 300+ drupal site users (cyclists):

`<html><body>

Warning | PHP max_input_vars setting | PHP limits the number of input variables in each form to 1,000 items. more
-- | -- | --
Warning | Trusted Host Setting | Not configured more
Info | Backdrop CMS | 1.26.3
Info | CKEditor 4 | Version: 4.22.1 more
Info | MySQL Database | MySQL, MariaDB, or equivalent version 5.7.42
Info | PHP | Version: 7.1.33 (PHP information)
Info | Telemetry | Enabled more
Info | Web server | Apache
OK | Access to update.php | Protected
OK | Backdrop CMS update notifications | Enabled
OK | Backdrop CMS update status | Up to date
OK | Cron maintenance tasks | Last run 3 hours 21 min ago (Run cron manually) more
OK | Database updates | Up to date
OK | Display error messages | Disabled more
OK | File system | Writable (public download method)
OK | GD library rotate and desaturate effects | bundled (2.1.0 compatible)
OK | jQuery | jQuery version 3.7.1 / jQuery UI version 1.13.2
OK | Module, theme, and layout updates | Up to date
OK | MySQL Database 4-byte UTF-8 support | Enabled more
OK | Node Access Permissions | Disabled (Rebuild permissions) more
OK | PHP extensions | Enabled: date, dom, filter, gd, hash, json, pcre, pdo, session, SimpleXML, SPL, xml
OK | PHP memory limit | 128M
OK | PHP register globals | Disabled
OK | Unicode library | PHP Mbstring Extension
OK | Upload progress | Client-side upload progress enabled


</body>
</html>`

**Comment by pierrenel** [comment]
Seeing the same issue :(

**Comment by laryn** [comment]
@Fiselier sorry for the delay, I missed your earlier reply. Thanks for bumping this up again @pierrenel  :smiley_cat: 

Can one or both of you test the latest code (not yet released but in the repo)? Let me know if you have questions on how to do that. If you report success I'll make a new release.
