### ISSUE TITLE
Remove useless update hooks

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/user_import#7]
In https://github.com/backdrop-contrib/user_import/blob/1.x-3.x/user_import.install there are a few useless update hooks. Anything that is not like hook_update_1xxx can be deleted.

**Comment by laryn** [comment]
Ah, good catch. I see that file needs a little cleanup in general. Thanks!

**Comment by laryn** [comment]
@herbdool Care to take a gander before I merge this? Does the mail system clean up here look correct to you?

https://github.com/backdrop-contrib/user_import/pull/8
